name: Deploy to GCP Cloud Storage (Without Key File)

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP (Workload Identity)
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}

      - name: Upload to Cloud Storage
        run: |
          gsutil -m rsync -r ./ gs://your-bucket-name
